apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: jenkins # Pastikan ini cocok dengan label di Pod Jenkins Anda
  ports:
  - name: http       # Port untuk UI Jenkins
    protocol: TCP
    port: 8080        # Port yang akan diakses oleh service secara internal
    targetPort: 8080    # Port pada container Jenkins untuk UI
    nodePort: 30007   # Sesuaikan dengan NodePort yang Anda inginkan atau yang sudah ada
  - name: jnlp        # Port untuk Jenkins agent/tunnel (JNLP)
    protocol: TCP
    port: 50000      # Port yang akan diakses oleh service secara internal
    targetPort: 50000  # Port pada container Jenkins untuk JNLP
    # nodePort: 3XXXX # Anda bisa menambahkan NodePort untuk JNLP jika perlu (opsional untuk tunnel)
