apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: devops-tools # Pastikan namespace ini benar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: devops-tools # Pastikan namespace ini benar
rules:
- apiGroups: [""] # "" adalah core API group
  resources:
  - pods
  - pods/log
  - pods/exec  # <--- TAMBAHKAN ATAU PASTIKAN INI ADA
  - services
  - deployments
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - secrets
  - configmaps
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
  - patch
- apiGroups: ["apps"]
  resources:
  - deployments
  - statefulsets
  - daemonsets
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
  - patch
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
  - patch
# Tambahkan apiGroups dan resources lain jika diperlukan oleh plugin atau pipeline Anda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: devops-tools # Pastikan namespace ini benar
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: devops-tools
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
