apiVersion: apps/v1
kind: Deployment
metadata:
  name: carvilla-web
  namespace: default
  labels:
    app: carvilla-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carvilla-web
  template:
    metadata:
      labels:
        app: carvilla-web
    spec:
      containers:
      - name: carvilla-web
        image: 10.34.7.115:30500/carvilla:${BUILD_NUMBER} # Baris ini akan diganti oleh pipeline
        ports:
        - containerPort: 80
          name: http
        resources: # <--- PASTIKAN INDENTASI INI SEJAJAR DENGAN 'ports:' dan 'image:'
          limits:
            cpu: "0.5"
            memory: "256Mi" # <--- KOREKSI INDENTASI DI SINI (SEJAJAR DENGAN 'cpu:' DI ATASNYA)
          requests:
            cpu: "0.2"
            memory: "128Mi"
        readinessProbe: # <--- PASTIKAN INDENTASI INI SEJAJAR DENGAN 'resources:'
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
