apiVersion: v1
kind: Service
metadata:
  name: carvilla-web-service
  namespace: default
  labels:
    app: carvilla-web
spec:
  type: NodePort
  selector:
    app: carvilla-web
  ports:
  - port: 80
    targetPort: 80
    # nodePort: (dihapus atau ganti ke rentang valid misal 30080)
